In [1]:
# Importing Librarys

import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
# Loading Data set

df = pd.read_csv("homeprices.csv")

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
# Handling NaN value

import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [6]:
# Fill NaN value

df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [7]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [9]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [10]:
# Coeff (m)

reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [11]:
# Intercept (b)

reg.intercept_

221323.0018654043

In [12]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [15]:
reg.predict([[2600,3,20]])

array([518217.63297611])

In [16]:
reg.predict([[2500,4,5]])

array([578876.03748933])

### EXERCISE

In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

FIND:

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score

In [17]:
# Importing librarys

import pandas as pd
import numpy as np
from sklearn import linear_model

In [18]:
# loading Dataset

df = pd.read_csv("hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [19]:
# Working on Experience column

df.experience = df.experience.fillna("Zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       Zero                    8.0                           9      50000
1       Zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [21]:
# Converting experience from word to number

from word2number import w2n
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [22]:
# Working on test_score column

import math
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [23]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [25]:
# Model Building

reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [26]:
# Q.no 1
reg.predict([[2,9,6]])

array([53713.86677124])

In [27]:
# Q.no 2
reg.predict([[12,10,10]])

array([93747.79628651])